### ISSUE TITLE
Advertise Service IPs

### ISSUE THREAD

**Issue by zzachattack2** [metallb/frr-k8s#92]
Is there a way to inject service-ip/external-ip routes into the outbound advertisements? 

Awesome project by the way! Love the ability to inject raw FRR configs.

**Comment by fedepaol** [comment]
Can you expand a bit the requirement?

**Comment by zzachattack2** [comment]
> Can you expand a bit the requirement? 

Kube-router's and cilium's bgp implementation both have a knob to advertise service-IPs and pod subnets outside of the cluster... I'm just not sure how to capture these for redistribution if they are not statically assigned.

**Comment by fedepaol** [comment]
> > Can you expand a bit the requirement?
> 
> Kube-router's and cilium's gobgp integration both have a knob to advertise service-IPs and pod subnets outside of the cluster... I'm just not sure how to capture these for redistribution if they are not statically assigned to a particular node.

yeah you'd need something with a node selector, and a controller that generates the config for a given node (talking about pod ips). Anyhow, you might be interested in https://github.com/metallb/frr-k8s which we are going to integrate in metallb soon-ish as a different bgp backend.
Closing this for now

**Comment by fedepaol** [comment]
> Did you mean to paste a different link?

nope, it's a frr based daemon with its own api, where you can advertise / receive what cidr you want. Still, the node based pod cidr is out of scope and another controller would be required, but it's better than the frr raw injection

**Comment by zzachattack2** [comment]
You pasted the link to the same project that we are discussing.

**Comment by zzachattack2** [comment]
> > You pasted the link to the same project that we are discussing.
> 
> 
> 
> LOL apologies. I came here from the email client, and I was absolutely sure this was a metallb issue, because this project is still being worked on and we did not make much noise about it.
> 
> 
> 
> So, to re-iterate, this is a bit lower level and you'd require something in the middle that configures it (such as metallb will do for lb services)

Haha no worries, I guess I did post the first "issue" :). I have cilium assigning external IPs to LB services, and just was not sure how to get those host routes into a table that FRR could advertise... but I think you're saying other CNI BGP implementations handle that part natively? Dang, but thanks!
